services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  name-service:
    build: .
    ports:
      - "5000:8000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/users

volumes:
  db_data:
    driver: local
