services:
  microservices-demo-name-mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: names
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  microservices-demo-name-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - microservices-demo-name-mysql
      - rabbitmq
    environment:
      DATABASE_URL: mysql+pymysql://root:password@microservices-demo-name-mysql:3306/names
      RABBITMQ_URL: amqp://rabbitmq:5672/

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local
