ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS names;
USE names;

CREATE TABLE IF NOT EXISTS names (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL
);
